#if !canImport(ObjectiveC)
import XCTest

extension IncomingMessageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IncomingMessageTests = [
        ("testDecodesServerHello", testDecodesServerHello),
        ("testDecodesServerMessage", testDecodesServerMessage),
        ("testDecodesServerPing", testDecodesServerPing),
        ("testDecodesServerPub", testDecodesServerPub),
        ("testDecodesServerReauth", testDecodesServerReauth),
        ("testDecodesServerRequest", testDecodesServerRequest),
        ("testDecodesServerRevoke", testDecodesServerRevoke),
        ("testDecodesServerSub", testDecodesServerSub),
        ("testDecodesServerUnsub", testDecodesServerUnsub),
        ("testDecodesServerUpdate", testDecodesServerUpdate),
    ]
}

extension NesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NesTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IncomingMessageTests.__allTests__IncomingMessageTests),
        testCase(NesTests.__allTests__NesTests),
    ]
}
#endif
